# Config file for Air (hot-reload)
[build]
  cmd = "go build -o ./tmp/main ." # Build command
  bin = "./tmp/main"               # Output binary
  full_bin = "./tmp/main"          # Full binary path
  exclude_dir = ["tmp", "vendor"]  # Exclude these directories
  include_ext = ["go", "tpl", "html", "css", "js"] # Watch these extensions
  delay = 1000                     # Delay in ms before restarting
  kill_delay = 500                 # Kill delay in ms before restart

[log]
  level = "debug" # Log level
  color = "true"  # Enable color in logs
