version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: simpleAuthDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - shared-data:/shared-data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/shared-data
    depends_on:
      db:
        condition: service_healthy

volumes:
  shared-data: