version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/shared-data
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: simpleAuthDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - shared-data:/shared-data

volumes:
  shared-data: