version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: DATABASE
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_server_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: SERVER
    ports:
      - "8080:8080"
