version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: DATABASE
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_server_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 40

  app:
    build: .
    container_name: SERVER
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
